Models/ErrorViewModel.cs
using System;

namespace Myimdb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Movie.cs
using System.Collections.Generic;

public class Movie
{
    public int Id { get; set; }
    public int Rank { get; set; }
    public string Title { get; set; }
    public int Year { get; set; }
    public string Storyline { get; set; }

    #region RETRIEVE
    public static List<Movie> SelectAll()
    {
        var movies = new List<Movie>() {
       new Movie() {
          Id = 1, Rank = 9, Title = "The Shawshank Redemption", Year = 1994, Storyline = "Two imprisoned men bond over a number of years..."
        },
        new Movie() {
          Id = 2, Rank = 9, Title = "The Godfather", Year = 1972, Storyline = "The aging patriarch of an organized crime dynasty..."
        },
        new Movie() {
          Id = 3, Rank = 9, Title = "The Godfather - Part II", Year = 1974, Storyline = "The early life and career of Vito Corleone in 1920s..."
        },
        new Movie() {
          Id = 4, Rank = 9, Title = "The Dark Knight", Year = 2008, Storyline = "When the menace known as the Joker wreaks havoc..."
        }};
        return movies;
    }
    #endregion
}

Models/ViewModels/MovieCreateViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Myimdb.Models.ViewModels
{
    public class MovieCreateViewModel
    {
        [Required(ErrorMessage = "Rank is required")]
        [Range(1, 10, ErrorMessage = "Rank should be in between {1} and {2}")]
        public int? Rank { get; set; }
        [Required(ErrorMessage = "Title of the movie is required")]
        [MaxLength(100, ErrorMessage = "Title can't be greater than {1} characters")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Release year is required")]
        [Range(1900, 2020, ErrorMessage = "Year of release should be in between {1} and {2}")]
        public int? Year { get; set; }
        [Required(ErrorMessage = "The storyline of the movie is required")]
        [MaxLength(200, ErrorMessage = "Storyline can't be greater than {1} characters")]
        public string Storyline { get; set; }

    }
}

Models/ViewModels/MovieListViewModel.cs
namespace Myimdb.Models.ViewModels
{
    public class MovieListViewModel
    {
        public int Rank { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }

    }

}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Myimdb.Models;
using Myimdb.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Myimdb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var movies = Movie.SelectAll().ConvertAll(m => new MovieListViewModel {Title = m.Title, Year = m.Year});
            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Myimdb.Models.ViewModels;

namespace Myimdb.Controllers
{
    public class MovieController : Controller
    {
        public ActionResult Index(string msg = null)
        {
            
            var movies = Movie.SelectAll().ConvertAll(movie => new MovieListViewModel { Rank = movie.Rank, Title = movie.Title, Year = movie.Year });

            ViewBag.Message = msg;
            return View(movies);
        }

        public ActionResult MovieOfTheResult()
        {
            return View();
        }

        public IActionResult MovieOfTheMonthResult()
        {
            var movieOfTheMonth = new MovieCreateViewModel{ Rank = 1, Title = "The Shawshank Redemption", Year = 1994 , Storyline = "Two imprisoned men bond over a number of years..." };
            return View(movieOfTheMonth);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MovieCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return RedirectToAction(nameof(Index), new
            {
                msg = "Movie created with success."
            });
        }
        
    }
}

Views/Home/Index.cshtml
@{
    @using Myimdb.Models.ViewModels;
    @model List<MovieListViewModel>

}

<!--<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>-->
<div>
    
    <div class="container">
        <h5>Movies of the month</h5>
        <div class="row text-center align-content-center">
            @foreach (var movie in Model)
            {
                <div class="col-md-3">
                    <div class="card my-card-large card-body">
                        <img class="align-content-md-center" src="~/img/movie-poster-placeholder.png" />
                        <div class="card-inverse bg-secondary">
                            <h5>
                                <a class="text-white-50" href="@string.Format("https://www.google.com/search?q={0}", movie.Title)"> @movie.Title (@movie.Year)</a>
                            </h5>
                        </div>
                    </div>
                </div>
            }
            <a asp-area="" asp-controller="Movie" asp-action="Index">
                See the complete list
                <i class="alert-heading">></i>
            </a>
        </div>
    </div>

</div>

Views/Movie/Create.cshtml
@model Myimdb.Models.ViewModels.MovieCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add movie</h1>

<h5>Please fill the movie data to add a new movie</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rank" class="control-label"></label>
                <input asp-for="Rank" class="form-control" />
                <span asp-validation-for="Rank" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Storyline" class="control-label"></label>
                <input asp-for="Storyline" class="form-control" />
                <span asp-validation-for="Storyline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Movie/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Myimdb.Models.ViewModels;
@model List<MovieListViewModel>

@{
    //var pi = 3.14;
    //var rnd = new Random();

    //var randomNumber = rnd.Next(1, 100);
    //var primes = new int[] { 1, 3, 5, 7 };

    ////Create anonymous movie type
    //var movie1 = new { Rank = 1, Title = "The Shawshank Redemption", Year = 1994 };
    //var movie2 = new { Rank = 2, Title = "The Godfather", Year = 1972 };
    //var movie3 = new { Rank = 3, Title = "The Godfather - Part II", Year = 1974 };
    //var movie4 = new { Rank = 4, Title = "The Dark Knight", Year = 2008 };
    //var movie5 = new { Rank = 5, Title = "Pulp Fiction", Year = 1994 };
    ////Create a list out of those 5 movies.
    //var moviesList = new[] { movie1, movie2, movie3, movie4, movie5 }.ToList();
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Movies</title>
</head>

<body>
    <div>
        <h1>Movies</h1>
        @*
            <div>The value of pi is @(pi)</div>
            <div>
            @if (randomNumber % 2 == 0)
            { // Par]
            <text> The generated random number @randomNumber is an even number </text>
            }
            else
            {
            @:The generated random number @randomNumber is an odd number
            }
            </div>
            List of prime numbers:<br />
            <ul>
            @foreach (var num in primes)
            {
            <li>@num</li>
            }
            </ul>*@

        @if (ViewBag.Message != null)
        {
            <div class="alert alert-info">
                <p>@ViewBag.Message</p>
            </div>
        }
        <b>Movies List</b>
        @*<table border="1">
            <tr>
            <th> Title </th>
            <th> Rank </th>
            <th> Year </th>
            </tr>
            @foreach (var movie in Model)
            {
            <tr>
            <td> @movie.Title </td>
            <td> @movie.Rank </td>
            <td> @movie.Year </td>
            </tr>

            }
            </table>*@
        <div class="container">
            <div class="row align-items-center">
                <div class="col">
                    Title
                </div>
                <div class="col">
                    Rank
                </div>
                <div class="col">
                    Year
                </div>
            </div>
            @foreach (var movie in Model)
            {
                <div class="row align-items-center">
                    <div class="col border-bottom">
                        <a href="@string.Format("https://www.google.com/search?q={0}", movie.Title)"> @movie.Title </a>
                    </div>
                    <hr />
                    <div class="col border-bottom">
                        @movie.Rank
                    </div>
                    <hr />
                    <div class="col border-bottom">
                        @movie.Year
                    </div>
                    <hr />
                </div>
            }
        </div>

        <a class="btn btn-info" asp-area="" asp-controller="Movie" asp-action="Create">
            <i class="fa-thin fa-user"></i>
                Add new movie
            </a>
        <div>
            <text>
                Click
                <a asp-controller="Movie" asp-action="MovieOfTheMonthResult">Here</a>
                to check out the movie of the month!
            </text>
        </div>
    </div>
</body>
</html>

Views/Movie/MovieOfTheMonthResult.cshtml
@model Myimdb.Models.ViewModels.MovieCreateViewModel

@{
    ViewData["Title"] = "MovieOfTheMonthResult";
}

<h1>Movie Of The Month Result</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <div class="col-d-flex justify-content-center">
        <div class="card">
            And the movie of the month is...
            <img class="my-card card-body" src="~/img/movie-poster-placeholder.png" />
            <div class="card-inverse">
                <h4 class="text-stroke">
                    @Html.DisplayFor(model => model.Title)
                </h4>
            </div>
        </div>
    </div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rank)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rank)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            <a href="@string.Format("https://www.google.com/search?q={0}", @Html.DisplayTextFor(model => model.Title))">
                @Html.DisplayFor(model => model.Title)
            </a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Storyline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Storyline)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Myimdb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <svg id="home_img" xmlns="http://www.w3.org/2000/svg" width="64" height="32" viewBox="0 0 64 32" version="1.1">
                        <g fill="#F5C518"><rect x="0" y="0" width="100%" height="100%" rx="4"></rect></g>
                        <g transform="translate(8.000000, 7.000000)" fill="#000000" fill-rule="nonzero">
                            <polygon points="0 18 5 18 5 0 0 0"></polygon>
                            <path d="M15.6725178,0 L14.5534833,8.40846934 L13.8582008,3.83502426 C13.65661,2.37009263 13.4632474,1.09175121 13.278113,0 L7,0 L7,18 L11.2416347,18 L11.2580911,6.11380679 L13.0436094,18 L16.0633571,18 L17.7583653,5.8517865 L17.7707076,18 L22,18 L22,0 L15.6725178,0 Z"></path><path d="M24,18 L24,0 L31.8045586,0 C33.5693522,0 35,1.41994415 35,3.17660424 L35,14.8233958 C35,16.5777858 33.5716617,18 31.8045586,18 L24,18 Z M29.8322479,3.2395236 C29.6339219,3.13233348 29.2545158,3.08072342 28.7026524,3.08072342 L28.7026524,14.8914865 C29.4312846,14.8914865 29.8796736,14.7604764 30.0478195,14.4865461 C30.2159654,14.2165858 30.3021941,13.486105 30.3021941,12.2871637 L30.3021941,5.3078959 C30.3021941,4.49404499 30.272014,3.97397442 30.2159654,3.74371416 C30.1599168,3.5134539 30.0348852,3.34671372 29.8322479,3.2395236 Z"></path><path d="M44.4299079,4.50685823 L44.749518,4.50685823 C46.5447098,4.50685823 48,5.91267586 48,7.64486762 L48,14.8619906 C48,16.5950653 46.5451816,18 44.749518,18 L44.4299079,18 C43.3314617,18 42.3602746,17.4736618 41.7718697,16.6682739 L41.4838962,17.7687785 L37,17.7687785 L37,0 L41.7843263,0 L41.7843263,5.78053556 C42.4024982,5.01015739 43.3551514,4.50685823 44.4299079,4.50685823 Z M43.4055679,13.2842155 L43.4055679,9.01907814 C43.4055679,8.31433946 43.3603268,7.85185468 43.2660746,7.63896485 C43.1718224,7.42607505 42.7955881,7.2893916 42.5316822,7.2893916 C42.267776,7.2893916 41.8607934,7.40047379 41.7816216,7.58767002 L41.7816216,9.01907814 L41.7816216,13.4207851 L41.7816216,14.8074788 C41.8721037,15.0130276 42.2602358,15.1274059 42.5316822,15.1274059 C42.8031285,15.1274059 43.1982131,15.0166981 43.281155,14.8074788 C43.3640968,14.5982595 43.4055679,14.0880581 43.4055679,13.2842155 Z"></path>
                        </g>
                    </svg>
                </a>
                <form class="navbar-search pull-left">
                    <div class="col-form-label">
                        <div class="input-group">
                            <input type="text" class="search-query">
                            <span class="input-group-btn">
                                <button class="btn btn-search text-white-50" type="button"> Search </button>
                            </span>
                        </div>
                    </div>
                </form>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Movie" asp-action="Create">Add new movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Movie" asp-action="MovieOfTheMonthResult">Movie of the month</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Myimdb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>